excluded:
 - Pods
disabled_rules:
- trailing_whitespace
opt_in_rules:
- vertical_whitespace_between_cases
line_length:
warning: 275
ignores_function_declarations: true
ignores_comments: true
ignores_interpolated_strings: true
ignores_urls: true
