# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Shotl-test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shotl-test
  # Networking
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  
  # Reactive
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  
  # switf utils
  pod 'Swinject'

  target 'Shotl-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Shotl-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
